# Generated by Django 2.0.1 on 2018-01-14 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shipping_address_1', models.CharField(max_length=260)),
                ('shipping_address_2', models.CharField(max_length=260)),
                ('shipping_postcode', models.CharField(max_length=10)),
                ('shipping_city', models.CharField(max_length=260)),
                ('shipping_state', models.CharField(max_length=3)),
                ('billing_address_1', models.CharField(max_length=260)),
                ('billing_address_2', models.CharField(max_length=260)),
                ('billing_postcode', models.CharField(max_length=10)),
                ('billing_city', models.CharField(max_length=260)),
                ('billing_state', models.CharField(max_length=3)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='oderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='oderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='oderitem',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductVariation'),
        ),
    ]
