# Generated by Django 2.0.1 on 2018-01-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='slug',
            field=models.CharField(default='slug', max_length=260),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='slug', max_length=260),
        ),
    ]
