# Generated by Django 2.0.1 on 2018-01-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180115_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='slug',
            field=models.CharField(default='slug', max_length=260, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(default='slug', max_length=260, unique=True),
        ),
    ]
